#include<stdio.h>
#include<conio.h>
#include<windows.h>

void waiting_time();
void gotoxy_m(int x, int y);

void waiting_time()
{
	gotoxy_m(42, 18);
	printf("бсбсбсбсбсбсбс");
	gotoxy_m(42, 19);
	printf("            бс");
	gotoxy_m(42, 20);
	printf("            бс");
	gotoxy_m(42, 21);
	printf("            бс");
	gotoxy_m(42, 22);
	printf("бсбсбсбсбсбсбс");
	gotoxy_m(42, 23);
	printf("            бс");
	gotoxy_m(42, 24);
	printf("            бс");
	gotoxy_m(42, 25);
	printf("            бс");
	gotoxy_m(42, 26);
	printf("бсбсбсбсбсбсбс");
	Sleep(250);
	gotoxy_m(42, 18);
	printf("бсбсбсбсбсбсбс");
	gotoxy_m(42, 19);
	printf("            бс");
	gotoxy_m(42, 20);
	printf("            бс");
	gotoxy_m(42, 21);
	printf("            бс");
	gotoxy_m(42, 22);
	printf("бсбсбсбсбсбсбс");
	gotoxy_m(42, 23);
	printf("бс            ");
	gotoxy_m(42, 24);
	printf("бс            ");
	gotoxy_m(42, 25);
	printf("бс            ");
	gotoxy_m(42, 26);
	printf("бсбсбсбсбсбсбс");
	Sleep(250);
	gotoxy_m(42, 18);
	printf("      бс      ");
	gotoxy_m(42, 19);
	printf("      бс      ");
	gotoxy_m(42, 20);
	printf("      бс      ");
	gotoxy_m(42, 21);
	printf("      бс      ");
	gotoxy_m(42, 22);
	printf("      бс      ");
	gotoxy_m(42, 23);
	printf("      бс      ");
	gotoxy_m(42, 24);
	printf("      бс      ");
	gotoxy_m(42, 25);
	printf("      бс      ");
	gotoxy_m(42, 26);
	printf("      бс      ");
	Sleep(250);
	gotoxy_m(42, 18);
	printf("бсбсбсбсбсбсбс");
	gotoxy_m(42, 19);
	printf("бс          бс");
	gotoxy_m(42, 20);
	printf("бс          бс");
	gotoxy_m(42, 21);
	printf("бс          бс");
	gotoxy_m(42, 22);
	printf("бс          бс");
	gotoxy_m(42, 23);
	printf("бс          бс");
	gotoxy_m(42, 24);
	printf("бс          бс");
	gotoxy_m(42, 25);
	printf("бс          бс");
	gotoxy_m(42, 26);
	printf("бсбсбсбсбсбсбс");
	Sleep(250);
	gotoxy_m(42, 18);
	printf("              ");
	gotoxy_m(42, 19);
	printf("              ");
	gotoxy_m(42, 20);
	printf("              ");
	gotoxy_m(42, 21);
	printf("              ");
	gotoxy_m(42, 22);
	printf("              ");
	gotoxy_m(42, 23);
	printf("              ");
	gotoxy_m(42, 24);
	printf("              ");
	gotoxy_m(42, 25);
	printf("              ");
	gotoxy_m(42, 26);
	printf("              ");
	Sleep(250);
}